name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build
        run: CI=1 npx expo export:web
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web-build
          branch: gh-pages
          
